@startuml
'https://plantuml.com/class-diagram

class Movie {
	 + getActors() : Stream<Actor>
	 + getGenres() : Stream<Genre>
	 + getName() : String
	 + getId() : int
	 + getPopularity() : double
	 + getReleaseDate() : LocalDate
}

class MovieDetail extends Movie{
    + getCompanies() : List<String>
    + getRuntime() : int
    + getRevenue() : long
    +  getBudget() : long
}

class Actor {
	+ getName() : String
	+ getId() : int
	+ getPopularity() : double
	+ getMovies() : Stream<Movie>
}

class Genre {
	+ getId() : int
	+ getName() : String
	+ getMovies() : Stream<Movie>
}

Genre      o- "*" Movie : movies
Movie      o- "*" Genre : genres
Movie      o- "*" Actor : actors
Actor      o- "*" Movie : movies
@enduml